services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb
      DATABASE_PASSWORD: mypassword
      APPLICATION_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
